# fly.toml file generated for horrortube on 2023-05-23T17:41:06Z

app = "horrortube"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  APP_URL = "https://horrortube.fly.dev"
  APP_NAME = "horrortube"
  APP_DEBUG = false
  DB_CONNECTION = "pgsql"
  DB_HOST = "db.daatbyukdqndhxyaubuh.supabase.co"  
  DB_PORT = 5432
  DB_DATABASE = "postgres"
  DB_USERNAME = "postgres"
  AWS_ACCESS_KEY_ID = "AKIA3KHKQYSEVALSEG6W"
  AWS_SECRET_ACCESS_KEY = "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"
  AWS_DEFAULT_REGION= "ap-northeast-1"
  AWS_BUCKET= "horrortube-images"
  AWS_USE_PATH_STYLE_ENDPOINT = "false"
  AWS_URL = "https://s3.ap-northeast-1.amazonaws.com/horrortube-images"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
